// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: byzantine.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ByzantineService_PropagateOrder_FullMethodName = "/byzantine.ByzantineService/PropagateOrder"
)

// ByzantineServiceClient is the client API for ByzantineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ByzantineServiceClient interface {
	// PropagateOrder is called to send an order (or report) for a given round.
	PropagateOrder(ctx context.Context, in *OrderMessage, opts ...grpc.CallOption) (*Ack, error)
}

type byzantineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewByzantineServiceClient(cc grpc.ClientConnInterface) ByzantineServiceClient {
	return &byzantineServiceClient{cc}
}

func (c *byzantineServiceClient) PropagateOrder(ctx context.Context, in *OrderMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ByzantineService_PropagateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ByzantineServiceServer is the server API for ByzantineService service.
// All implementations must embed UnimplementedByzantineServiceServer
// for forward compatibility.
type ByzantineServiceServer interface {
	// PropagateOrder is called to send an order (or report) for a given round.
	PropagateOrder(context.Context, *OrderMessage) (*Ack, error)
	mustEmbedUnimplementedByzantineServiceServer()
}

// UnimplementedByzantineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedByzantineServiceServer struct{}

func (UnimplementedByzantineServiceServer) PropagateOrder(context.Context, *OrderMessage) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PropagateOrder not implemented")
}
func (UnimplementedByzantineServiceServer) mustEmbedUnimplementedByzantineServiceServer() {}
func (UnimplementedByzantineServiceServer) testEmbeddedByValue()                          {}

// UnsafeByzantineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ByzantineServiceServer will
// result in compilation errors.
type UnsafeByzantineServiceServer interface {
	mustEmbedUnimplementedByzantineServiceServer()
}

func RegisterByzantineServiceServer(s grpc.ServiceRegistrar, srv ByzantineServiceServer) {
	// If the following call pancis, it indicates UnimplementedByzantineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ByzantineService_ServiceDesc, srv)
}

func _ByzantineService_PropagateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByzantineServiceServer).PropagateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ByzantineService_PropagateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByzantineServiceServer).PropagateOrder(ctx, req.(*OrderMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ByzantineService_ServiceDesc is the grpc.ServiceDesc for ByzantineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ByzantineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "byzantine.ByzantineService",
	HandlerType: (*ByzantineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PropagateOrder",
			Handler:    _ByzantineService_PropagateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "byzantine.proto",
}
