// protofiles/loadbalancer.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: loadbalancer.proto

package lb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadBalancer_RegisterBackend_FullMethodName = "/lb.LoadBalancer/RegisterBackend"
	LoadBalancer_ReportLoad_FullMethodName      = "/lb.LoadBalancer/ReportLoad"
	LoadBalancer_GetBestServer_FullMethodName   = "/lb.LoadBalancer/GetBestServer"
)

// LoadBalancerClient is the client API for LoadBalancer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Load Balancer service definition.
type LoadBalancerClient interface {
	RegisterBackend(ctx context.Context, in *RegisterBackendRequest, opts ...grpc.CallOption) (*RegisterBackendResponse, error)
	ReportLoad(ctx context.Context, in *ReportLoadRequest, opts ...grpc.CallOption) (*ReportLoadResponse, error)
	GetBestServer(ctx context.Context, in *GetBestServerRequest, opts ...grpc.CallOption) (*GetBestServerResponse, error)
}

type loadBalancerClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadBalancerClient(cc grpc.ClientConnInterface) LoadBalancerClient {
	return &loadBalancerClient{cc}
}

func (c *loadBalancerClient) RegisterBackend(ctx context.Context, in *RegisterBackendRequest, opts ...grpc.CallOption) (*RegisterBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBackendResponse)
	err := c.cc.Invoke(ctx, LoadBalancer_RegisterBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadBalancerClient) ReportLoad(ctx context.Context, in *ReportLoadRequest, opts ...grpc.CallOption) (*ReportLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportLoadResponse)
	err := c.cc.Invoke(ctx, LoadBalancer_ReportLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadBalancerClient) GetBestServer(ctx context.Context, in *GetBestServerRequest, opts ...grpc.CallOption) (*GetBestServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBestServerResponse)
	err := c.cc.Invoke(ctx, LoadBalancer_GetBestServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadBalancerServer is the server API for LoadBalancer service.
// All implementations must embed UnimplementedLoadBalancerServer
// for forward compatibility.
//
// The Load Balancer service definition.
type LoadBalancerServer interface {
	RegisterBackend(context.Context, *RegisterBackendRequest) (*RegisterBackendResponse, error)
	ReportLoad(context.Context, *ReportLoadRequest) (*ReportLoadResponse, error)
	GetBestServer(context.Context, *GetBestServerRequest) (*GetBestServerResponse, error)
	mustEmbedUnimplementedLoadBalancerServer()
}

// UnimplementedLoadBalancerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadBalancerServer struct{}

func (UnimplementedLoadBalancerServer) RegisterBackend(context.Context, *RegisterBackendRequest) (*RegisterBackendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBackend not implemented")
}
func (UnimplementedLoadBalancerServer) ReportLoad(context.Context, *ReportLoadRequest) (*ReportLoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportLoad not implemented")
}
func (UnimplementedLoadBalancerServer) GetBestServer(context.Context, *GetBestServerRequest) (*GetBestServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestServer not implemented")
}
func (UnimplementedLoadBalancerServer) mustEmbedUnimplementedLoadBalancerServer() {}
func (UnimplementedLoadBalancerServer) testEmbeddedByValue()                      {}

// UnsafeLoadBalancerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadBalancerServer will
// result in compilation errors.
type UnsafeLoadBalancerServer interface {
	mustEmbedUnimplementedLoadBalancerServer()
}

func RegisterLoadBalancerServer(s grpc.ServiceRegistrar, srv LoadBalancerServer) {
	// If the following call pancis, it indicates UnimplementedLoadBalancerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadBalancer_ServiceDesc, srv)
}

func _LoadBalancer_RegisterBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadBalancerServer).RegisterBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadBalancer_RegisterBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadBalancerServer).RegisterBackend(ctx, req.(*RegisterBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadBalancer_ReportLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadBalancerServer).ReportLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadBalancer_ReportLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadBalancerServer).ReportLoad(ctx, req.(*ReportLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadBalancer_GetBestServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadBalancerServer).GetBestServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadBalancer_GetBestServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadBalancerServer).GetBestServer(ctx, req.(*GetBestServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadBalancer_ServiceDesc is the grpc.ServiceDesc for LoadBalancer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadBalancer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lb.LoadBalancer",
	HandlerType: (*LoadBalancerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBackend",
			Handler:    _LoadBalancer_RegisterBackend_Handler,
		},
		{
			MethodName: "ReportLoad",
			Handler:    _LoadBalancer_ReportLoad_Handler,
		},
		{
			MethodName: "GetBestServer",
			Handler:    _LoadBalancer_GetBestServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadbalancer.proto",
}
